### ISSUE TITLE
Works great, but doesn't survive a logout/reboot. 

### ISSUE THREAD

**Issue by rickthms** [gnikolaos/ulauncher-window-manager#2]
After installing, works great, as intended. Love it!

But stops working after I logout and back in again (or reboot). Shows as being installed in ulauncher, Window Commander extension still installed etc, but ulauncher-window-manager shortcuts just doesn't work. They show up in th ulauncher popup as expected, but their action does not occur.

If I remove ulauncher-window-manager from within uluancher and reinstall (without having to log out), ulauncher-window-manager shortcuts start working again as normal.

- Ubuntu 24.04 LTS (updated)
- Nothing custom about the system

Extensions installed:

- Bing Wallpaper
- Disconnect Wifi
- Extension List
- Fullscreen Avoider
- Just Perfection
- No overview at start-up
- One Thing
- OpenWeather Refined
- Panel World Clock (Lite)
- Status Area Horizontal Spacing
- Tailscale Status
- Ubuntu Dock
- Ubuntu Tiling Assistant
- Unblank lock screen
- Window Commander

Any ideas? Please let me know if anything I can do to help debug, log files, etc. 

Thank you!
-Rick

**Comment by gnikolaos** [comment]
I will have a look tomorrow.

**Comment by gnikolaos** [comment]
@rickthms Can you check if you have the latest versions of window-commander and ulauncher-window-manager? And which version of ulauncher are you using?

Also, when the extension stops working can you try to open a terminal and run the below 2 commands?

```gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/WindowCommander --method org.gnome.Shell.Extensions.WindowCommander.List```

pick the id of a window from the above command and use it to run the next one:
```gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/WindowCommander --method org.gnome.Shell.Extensions.WindowCommander.Place add_the_id_here 0 34 800 600```


Is the window moving by using the above commands?

**Comment by rickthms** [comment]
> @rickthms Can you check if you have the latest versions of window-commander and ulauncher-window-manager? And which version of ulauncher are you using?

- Ulauncher: v5.15.7
- Window Commander: v4
```
$ gnome-extensions info window-commander@gnikolaos.gr
window-commander@gnikolaos.gr
  Name: Window Commander
  Description: Provides a D-Bus interface for managing and controlling windows, including listing, resizing, moving, and workspace management
  Path: /home/rickt/.local/share/gnome-shell/extensions/window-commander@gnikolaos.gr
  URL: https://github.com/gnikolaos/window-commander
  Version: 4
  Enabled: Yes
  State: ACTIVE
```
- Ulauncher-Window-Manager: not exactly sure how to determine exact version number, but the dropdown in the Save menu within Ulauncher for UWM shows commit 2d4c206

> Also, when the extension stops working can you try to open a terminal and run the below 2 commands?
> 
> `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/WindowCommander --method org.gnome.Shell.Extensions.WindowCommander.List`
> 
> pick the id of a window from the above command and use it to run the next one: `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/WindowCommander --method org.gnome.Shell.Extensions.WindowCommander.Place add_the_id_here 0 34 800 600`
> 
> Is the window moving by using the above commands?

yes - the windows move! i tried various different window IDs, and they all were successfully resized and placed close to top left of my main window. 

i also tried using ulauncher-window-manager's hotkeys on the exact same window(s) i just moved using those Window Command place commands making sure my mouse focus was within them, and no response. just to check, i then moved the window(s) away from top left, re-ran the gdbus command and the windows were indeed moved back to top left. 

so it does appear that the Window Commander place commands are indeed working! 

i'm going to temporarily remove my other extensions and keep testing UWM, i'd like to remove variables from the mix to help you narrow this down.

let me know if I can provide any other info!

-RMT

**Comment by gnikolaos** [comment]
@rickthms We can try one more thing. Kill the running ulauncher (you can use the System Monitor app for that) and run the app again from a terminal with that command: `ulauncher --dev -v`. Then execute a random place command (Left Half for example), after that hit CTRL + C to terminate the app and check the log output in your terminal. Paste it here if possible. Also, have you overridden the default keywords in Ulauncher’s preferences for this extension?

**Comment by rickthms** [comment]
here it is. i did use the "Left Half" command. i'll keep running in dev mode to get these debug logs, hopefully i'll be able to trigger whatever it is i'm doing to cause things to stop and then get those logs to you as well! thank you!

```
$ ulauncher --dev -v
2024-12-26 07:46:40,022 | INFO | ulauncher: main() | Ulauncher version 5.15.7
2024-12-26 07:46:40,022 | INFO | ulauncher: main() | Extension API version 2.0.0
2024-12-26 07:46:40,022 | INFO | ulauncher: main() | GTK+ 3.24.41
2024-12-26 07:46:40,022 | INFO | ulauncher: main() | Is Wayland: False
2024-12-26 07:46:40,023 | INFO | ulauncher: main() | Wayland compatibility: off
2024-12-26 07:46:40,099 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2024-12-26 07:46:40,105 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2024-12-26 07:46:40,106 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2024-12-26 07:46:40,106 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2024-12-26 07:46:40,107 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2024-12-26 07:46:40,108 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2024-12-26 07:46:40,108 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2024-12-26 07:46:40,108 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2024-12-26 07:46:40,108 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2024-12-26 07:46:40,108 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2024-12-26 07:46:40,114 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2024-12-26 07:46:40,115 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 2560, H: 1440
2024-12-26 07:46:40,115 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 2560, Y: 726, W: 1920, H: 1080
2024-12-26 07:46:40,135 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2024-12-26 07:46:40,141 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2024-12-26 07:46:40,142 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2024-12-26 07:46:40,162 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.devkleber.ulauncher-open-link" started. PID 1159876
2024-12-26 07:46:40,166 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.kleber-swf.ulauncher-toggle-dnd" started. PID 1159878
2024-12-26 07:46:40,181 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.floydjohn.ulauncher-chrome-profiles" started. PID 1159880
2024-12-26 07:46:40,184 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.skykooler.ulauncher-conversion" started. PID 1159882
2024-12-26 07:46:40,200 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-emoji" started. PID 1159888
2024-12-26 07:46:40,201 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.gnikolaos.ulauncher-window-manager" started. PID 1159884
2024-12-26 07:46:40,201 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-timer" started. PID 1159886
2024-12-26 07:46:40,212 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ultiblog.ulauncher-password-generator" started. PID 1159890
2024-12-26 07:46:40,228 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.eckhoff42.ulauncher-favorite-directories" started. PID 1159892
2024-12-26 07:46:40,229 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 88 apps in cache
2024-12-26 07:46:40,339 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Alt>a
2024-12-26 07:46:40,390 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 88 apps in the system
2024-12-26 07:46:40,391 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.25 seconds
2024-12-26 07:46:40,408 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2024-12-26 07:46:40,653 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.gnikolaos.ulauncher-window-manager" connected
2024-12-26 07:46:40,654 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.gnikolaos.ulauncher-window-manager"
com.github.gnikolaos.ulauncher-window-manager | 2024-12-26 07:46:40,655 | INFO | websocket: info() | Websocket connected
com.github.gnikolaos.ulauncher-window-manager | 2024-12-26 07:46:40,655 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,731 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.floydjohn.ulauncher-chrome-profiles" connected
2024-12-26 07:46:40,733 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.floydjohn.ulauncher-chrome-profiles"
com.github.floydjohn.ulauncher-chrome-profiles | 2024-12-26 07:46:40,734 | INFO | websocket: info() | Websocket connected
com.github.floydjohn.ulauncher-chrome-profiles | 2024-12-26 07:46:40,734 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,749 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ultiblog.ulauncher-password-generator" connected
2024-12-26 07:46:40,751 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ultiblog.ulauncher-password-generator"
com.github.ultiblog.ulauncher-password-generator | 2024-12-26 07:46:40,754 | INFO | websocket: info() | Websocket connected
com.github.ultiblog.ulauncher-password-generator | 2024-12-26 07:46:40,758 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,770 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.devkleber.ulauncher-open-link" connected
2024-12-26 07:46:40,772 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.devkleber.ulauncher-open-link"
com.github.devkleber.ulauncher-open-link | 2024-12-26 07:46:40,773 | INFO | websocket: info() | Websocket connected
com.github.devkleber.ulauncher-open-link | 2024-12-26 07:46:40,774 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,778 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.kleber-swf.ulauncher-toggle-dnd" connected
2024-12-26 07:46:40,781 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.kleber-swf.ulauncher-toggle-dnd"
com.github.kleber-swf.ulauncher-toggle-dnd | 2024-12-26 07:46:40,782 | INFO | websocket: info() | Websocket connected
com.github.kleber-swf.ulauncher-toggle-dnd | 2024-12-26 07:46:40,783 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,788 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.skykooler.ulauncher-conversion" connected
2024-12-26 07:46:40,791 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.skykooler.ulauncher-conversion"
com.github.skykooler.ulauncher-conversion | 2024-12-26 07:46:40,792 | INFO | websocket: info() | Websocket connected
com.github.skykooler.ulauncher-conversion | 2024-12-26 07:46:40,793 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,794 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ulauncher.ulauncher-emoji" connected
2024-12-26 07:46:40,795 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ulauncher.ulauncher-emoji"
2024-12-26 07:46:40,796 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.eckhoff42.ulauncher-favorite-directories" connected
com.github.ulauncher.ulauncher-emoji | 2024-12-26 07:46:40,796 | INFO | websocket: info() | Websocket connected
com.github.ulauncher.ulauncher-emoji | 2024-12-26 07:46:40,796 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,797 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.eckhoff42.ulauncher-favorite-directories"
com.github.eckhoff42.ulauncher-favorite-directories | 2024-12-26 07:46:40,797 | INFO | websocket: info() | Websocket connected
com.github.eckhoff42.ulauncher-favorite-directories | 2024-12-26 07:46:40,798 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:40,818 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ulauncher.ulauncher-timer" connected
2024-12-26 07:46:40,819 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ulauncher.ulauncher-timer"
com.github.ulauncher.ulauncher-timer | 2024-12-26 07:46:40,819 | INFO | websocket: info() | Websocket connected
com.github.ulauncher.ulauncher-timer | 2024-12-26 07:46:40,819 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2024-12-26 07:46:48,357 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/UlauncherWindow.py", line 183, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
                        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 23, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3/dist-packages/ulauncher/utils/db/KeyValueDb.py", line 38, in open
    records = pickle.load(reader)
              ^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
2024-12-26 07:46:48,442 | WARNING | ulauncher.utils.image_loader: check_icon_name() | Icon theme is broken or incomplete. Substituting "discord" for "discord"
2024-12-26 07:46:48,464 | WARNING | ulauncher.utils.image_loader: check_icon_name() | Icon theme is broken or incomplete. Substituting "vscode" for "vscode"
2024-12-26 07:46:48,593 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2024-12-26 07:46:48,626 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2024-12-26 07:46:48,638 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 9 results
2024-12-26 07:46:48,823 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 7 results
2024-12-26 07:46:50,277 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 7 results
2024-12-26 07:46:50,484 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 4 results
2024-12-26 07:46:50,648 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2024-12-26 07:46:50,815 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2024-12-26 07:46:50,978 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2024-12-26 07:46:53,202 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.gnikolaos.ulauncher-window-manager"
com.github.gnikolaos.ulauncher-window-manager | 2024-12-26 07:46:53,253 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
com.github.gnikolaos.ulauncher-window-manager | 2024-12-26 07:46:53,254 | DEBUG | ulauncher.api.client.Client: send() | Send message
2024-12-26 07:46:53,255 | DEBUG | ulauncher.api.server.ExtensionController: handleMessage() | Incoming response (KeywordQueryEvent, HideWindowAction) from "com.github.gnikolaos.ulauncher-window-manager"
2024-12-26 07:46:53,257 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
com.github.gnikolaos.ulauncher-window-manager | 2024-12-26 07:46:53,279 | INFO | __main__: WindowManagerAction() | selected_action details: x:74, y:32, width:1243, height:1408
```

**Comment by rickthms** [comment]
UPDATE: everything worked 100%, with no problems whatsoever for ~2 weeks until i just now logged out to upgrade some Gnome shell extensions. logging in, ULWM doesn't appear to work. active ulauncher procs after login:

```
rickt    2154450  1.5  0.5 1627336 83836 ?       Sl   12:46   0:01 /usr/bin/python3 /usr/bin/ulauncher --hide-window --hide-window
rickt    2154836  0.3  0.3 316572 54272 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.devkleber.ulauncher-open-link/main.py
rickt    2154838  0.3  0.3 316556 54528 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.kleber-swf.ulauncher-toggle-dnd/main.py
rickt    2154840  0.3  0.3 316904 54516 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.floydjohn.ulauncher-chrome-profiles/main.py
rickt    2154842  0.3  0.3 316628 54244 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.skykooler.ulauncher-conversion/main.py
rickt    2154844  0.2  0.2 141264 35712 ?        S    12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.gnikolaos.ulauncher-window-manager/main.py
rickt    2154846  0.3  0.3 390272 54332 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.ulauncher.ulauncher-timer/main.py
rickt    2154849  0.3  0.3 318388 56264 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.ulauncher.ulauncher-emoji/main.py
rickt    2154850  0.3  0.3 316572 53560 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.ultiblog.ulauncher-password-generator/main.py
rickt    2154853  0.3  0.3 316720 54500 ?        Sl   12:46   0:00 /usr/bin/python3 /home/rickt/.local/share/ulauncher/extensions/com.github.eckhoff42.ulauncher-favorite-directories/main.py
```

as soon as i kill active ulauncher  and restart with `ulauncher --dev -v`, everything is fine again. some problem with startup? i'm working on a work problem right now, i'll dig into the logs later and update if i find anything!

-RMT

**Comment by gnikolaos** [comment]
According to your ulauncher log: 2024-12-26 07:46:40,022 | INFO | ulauncher: main() | **Is Wayland: False**). 

I think there are two cases: 

1.  Sometime when you log in you select to use ubuntu on Xorg, my extension is not supporting Xorg yet so it doesn't work as expected. 
2. You are using Wayland but for some weird reason ulauncher can't recognize that and it prints the "Is Wayland: False" in its log leading to unexpected behavior.

Nevertheless, I will setup a VM to play arround this, I want the extension to be able to work as it should with Xorg too...
